
services:

  db:
    image: pgvector:pg17-trixie
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: tmpfs
       target: /Users/abrar/Documents/CoVar/translator/Embeddings_Service/emb_db/data
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_EXTENSIONS: pgvector